= Map

A map is a data structure to store pairs of data: *key* and *value*. In an array, you can only store values. The array’s key is always the position index. However, in a *Map* the key can be whatever you want.

IMPORTANT: Map is a data structure that _maps_ *keys* to *values*.

Many languages have maps already built-in. JavaScript/Node has `Map`:

.JavaScript Built-in Map Usage
[source, javascript]
----
include::{codedir}/data-structures/maps/map.js[tag=snippet, indent=0]
----

The attractive part of Maps is that they are very performant usually *O(1)* or *O(log n)* depending on the implementation. We can implement the maps using two different techniques:

* *HashMap*: it’s a map implementation using an *array* and *hash function*. The job of the hash function is to convert the key into an index that contains the matching data. Optimized HashMap can have an average runtime of *O(1)*.
* *TreeMap*: it’s a map implementation that uses a self-balanced Binary Search Tree (red-black tree). The BST nodes store the key, and the value and nodes are sorted by key guaranteeing an *O(log n)* look up.
