= Algorithmic Toolbox

Have you ever given a programming problem and freeze without knowing where to start?
Well, in this section we are going to give some tips, so you don't get stuck while coding.

TIP: Don't start coding right away. First, solve the problem, then write the code.

.Steps to solve algorithmic problems
. *Understand* the requirements. Reframe it in your own words.
. Draw a *simple example* (no edge cases yet)
. Brainstorm
.. How would you solve this problem *manually*? (without a computer) Is there any formula or theorem you can use?
.. Is there any heuristics (largest, smallest, best ratio) or can you spot a pattern to solve this problem using a <<Greedy Algorithms, greedy algorithm>>?
.. Can you address the simple base case and generalize for other cases using a *recursive solution*?
.. Do you have to generate multiple solutions or try different paths? Try <<Backtracking>>.
.. If anything else fails, how would you solve it the dumbest way possible (brute force). We can optimize it later.
. Optimize the solution.
.. Re-read requirements and see if you can take advantage of anything. E.g. is the array sorted?
.. Do you have a bunch of overlapping problems? Try <<Dynamic Programming>>.
.. Can you trade-off space for speed? Use a <<HashMap, Map>> to speed up results
. Test your algorithm with multiple examples
. *Code*, yes, now you can code.
.. Modularize your code with functions (don't do it all in one giant function please 🙏)
. Test your code.
.. Choose a typical input and test against your code.
.. Brainstorm about edge cases (empty, null values, overflows,
.. How would scale your code?

These steps should get you going even with the toughest algorithmic problems.

Stay effective!
