= Bubble Sort

Bubble sort is a simple sorting algorithm that "bubbles up" the biggest values to the right side of the array.

== Bubble Sort Implementation

Bubble sort can be implemented in any programming language. This are the general steps that this sorting algorithm follows:

.Bubble Sort Algorithm
. It moves one element at a time (from left to right). Everything on the left of the current element is already sorted, while everything to the right is not.
. Start with the first element and make it the current element.
. Compare elements to right of the current element.
. Bubble up big values to the right of the array.
.. Swap elements if the previous element is bigger than the previous one.
. Move the current pointer to the next element and repeat for the rest of the array


Let's convert these words into code!

.Bubble Sort implementation in JavaScript
[source, javascript]
----
include::{codedir}/algorithms/sorting/bubble-sort.js[tag=sort, indent=0]
----
<1> Convert any kind of iterable (array, sets, etc.) into an array or if is already and array it clones it so the input is not modified.
<2> Goes through all the elements in the array
<3> *Compares in pairs* (current vs next element) and swap them only if they are out of order. Bubbles up largest
<4> If no swap was needed that means everything is sorted (this make this sorting adaptive, if everything is sorted it will be _O(n)_)
<5> If a swap as performed means that the largest element is all the way to the right side and no need compare it anymore, thus `array.length - left`.

Bubble sort has a <<Quadratic>> running time, as you might infer from the nested for-loop.

== Bubble Sort Properties

- <<Stable>>: [big]#✅# Yes
- <<In-place>>: [big]#✅# Yes
- <<Online>>: [big]#✅# Yes
- <<Adaptive>>: [big]#✅# Yes
- Time Complexity: [big]#⛔️# <<Quadratic>> _O(n^2^)_
- Space Complexity: [big]#✅# <<Constant>> _O(1)_
