= Bubble Sort

Bubble sort is a simple sorting algorithm that "bubbles up" the biggest values to the right side of the array.

== Bubble Sort Implementation

Bubble sort can be implemented in any programming language. This are the general steps that this sorting algorithm follows:

.Bubble Sort Algorithm
. It moves one element at a time (from left to right). Everything on the left of the current element is already sorted, while everything to the right is not.
. Start with the first element and make it the current element.
. Compare elements to right of the current element.
. Bubble up big values to the right of the array.
.. Swap elements if the previous element is bigger than the previous one.
. Move the current pointer to the next element and repeat for the rest of the array


Let's convert these words into code!

.Bubble Sort implementation in JavaScript
[source, javascript]
----
include::{codedir}/algorithms/sorting/bubble-sort.js[tag=sort, indent=0]
----
<1> Convert any kind of iterable (array, sets, etc.) into an array
<2> Start on the first element (position 0)
<3> Start scanning elements that are to the right of the current element.
<4> If the previous element is bigger than the previous one, then swap them. This is called bubbling up bigger values to the right.

Bubble sort has a <<Quadratic>> running time, as you might infer from the nested for-loop.

== Bubble Sort Properties

- <<Stable>>: [big]#✅# Yes
- <<In-place>>: [big]#✅# Yes
- <<Online>>: [big]#✅# Yes
- <<Adaptive>>: [big]#✅# Yes
- Time Complexity: [big]#⛔️# <<Quadratic>> _O(n^2^)_
- Space Complexity: [big]#✅# <<Constant>> _O(1)_
