ifndef::imagesdir[]
:imagesdir: ../images
:codedir: ../../src
endif::[]

= Fibonacci Sequence with Dynamic Programming
(((Fibonacci)))
Let's solve the same Fibonacci problem but this time with dynamic programming.

When we have recursive functions doing duplicated work is the perfect place for a dynamic programming optimization. We can save (or cache) the results of previous operations and speed up future computations.

.Recursive Fibonacci Implemenation using Dynamic Programming
[source, javascript]
----
include::{codedir}/algorithms/fibanacci-dynamic-programming.js[tag=snippet,indent=0]
----

This implementation checks if we already calculated the value, if so it will save it for later use.

[graphviz, Recursive Fibonacci call tree with dp, png]
....
graph G {
    "fib(5)" -- { "fib(4)" }
    "fib(4)" -- { "fib(3)" }
    "fib(3)" -- { "fib(2)" }
    "fib(2)" -- { "fib(1)", "fib(0)" }
}
....

This graph looks pretty linear now. It's runtime _O(n)_!
(((Linear)))
(((Runtime, Linear)))

(((Memoization)))
TIP: Saving previous results for later is a technique called "memoization". This is very common to optimize recursive algorithms with overlapping subproblems. It can make exponential algorithms linear!
