= Graph Search

Graph search allows you to visit all the elements connected given a starting node. There are two ways to navigate the graph, one is using Depth-First Search (DFS) and the other one is Breadth-First Search (BFS). Let's see the difference.

== Depth-First Search for Graphs

With Depth-First Search (DFS) we go deep before going wide.

// TODO: add arrows to show DFS and create another one for BFS

[graphviz, dfs-graph, png]
....
digraph G {

     node [fillcolor="#F8E71C" style=filled shape=circle] 0;
     node [fillcolor="#F5A623"] 1;
     node [fillcolor="#B8E986"] 2;
     node [fillcolor="#BD10E0"] 3;
     node [fillcolor="#50E3C2"] 4;
     node [fillcolor="#4A90E2"] 5;
    //  node [fillcolor="#FF5252"] 6;

        0 -> 5
        0 -> 4
        0 -> 1
        1 -> 4
        1 -> 3
        2 -> 1
        3 -> 4
        3 -> 2

    label="DFS"

    { rank=same; 3, 1 }
    { rank=same; 0, 4 }

}
....

== Breadth-First Search for Graphs

With Breadth-First Search (BFS) we go wide before going deep.

// TODO: BFS traversal

== Depth-First Search vs Breadth-First Search in a Graph

DFS and BFS can implementation can be almost identical the difference is the underlying data structured. In our implementation, we have a generic `graphSearch` where we pass the first element to start the search the data structure that we can to use:

.DFS and BFS implemenation
[source, javascript]
----
include::{codedir}/data-structures/graphs/graph.js[tag=graphSearch,indent=0]
----

Using an <<Stack>> (LIFO) for DFS will make use keep visiting the last node children, while having a <<Queue>> (FIFO) will allows to visit adjacent nodes first and "queue" their children for later visting.

TIP: you can also implement the DFS as a recursive function, similar to what we did in the <<Depth-First Search for Binary Tree, DFS for trees>>.

You might wonder what's the difference between search algorithms in a tree and a graph? Check out the next section.

== DFS/BFS on Tree vs Graph

The difference between searching a tree and a graph is that the tree has always an starting point (root node). However, in a graph you can start searching anywhere. There's no root in graph.

NOTE: Every tree is a graph but not every graph is a tree.
