= Quicksort

Quicksort is an efficient recursive sorting algorithm that uses <<Divide and Conquer, divide and conquer>> paradigm to sort faster. It can be implemented in-place so it doesn't require additonal memory.

indexterm:[Divide and Conquer]

In practice quicksort outperforms efficient sorting algorithms like <<Merge Sort>>. And, of course, It also outperforms simple sorting algorithms like <<Selection Sort>>, <<Insertion Sort>> and <<Bubble Sort>>.

Quicksort basically picks a "pivot" element (preferably random) and move all the elements that are smaller than the pivot to the right and the ones that are bigger to the left. It does this recursively until all the array is sorted.

== Quicksort Implementation

Quicksort implementation uses the divide-and-conquer in the following way:

.Quicksort Algorithm
. Pick a "pivot" element (at random)
. Move everything that is lower than the pivot to the left and everything that is bigger than the pivot to the right.
. Recursively repeat step 1 and 2, the sub-arrays on the left and on the right WITHOUT including the pivot.

Let's convert these words into code!

.Quicksort implementation in JavaScript (QuickSort)
[source, javascript]
----
include::{codedir}/algorithms/sorting/quick-sort.js[tag=quickSort, indent=0]
----
<1> Partition: picks a pivot and find the index where the pivot will be when the array is sorted.
<2> Do the partition of the sub-array at the left of the pivot.
<3> Do the partition of the sub-array at the right of the pivot.
<4> Only do the partition when there's something to divide.

The real heavy-lifting is don in the partion function. Let's implement that:

.Quicksort implementation in JavaScript (partition)
[source, javascript]
----
include::{codedir}/algorithms/sorting/Quick-sort.js[tag=partition, indent=0]
----
<1> Make the rightmost element as the pivot.
<2> This is the place holder for the final pivot index. We start in low and as we move all the lower elements to the left we will get the final place where the pivot should be.
<3> Move one element at a time comparing it to the pivot value.
<4> If the current element value is less than the pivot, then increment pivot index (pivot should be place after all the lower values). We also swap the value before incrementing because current element that is lower than the pivot to be at its left side.

Merge sort has a _O(n log n)_ running time. For more details about the how to extract the runtime go to <<Linearithmic>>.

== Quicksort Properties

- <<Stable>>: [big]#✅# Yes
- <<In-place>>: [big]#✅# Yes
- <<Adaptive>>: [big]#️❌# No, mostly sorted array takes the same time O(n log n).
- <<Online>>: [big]#️❌# No, the pivot element can be choose at random.
- Recursive: Yes
- Time Complexity: [big]#✅# <<Linearithmic>> _O(n log n)_
- Space Complexity: [big]#⚠️# <<Linear>> _O(n)_

indexterm:[Space Complexity, Linear]

// Resources:
// https://www.khanacademy.org/computing/computer-science/algorithms/quick-sort/a/linear-time-partitioning
// https://www.khanacademy.org/computing/computer-science/algorithms/quick-sort/a/overview-of-quicksort
// https://algs4.cs.princeton.edu/23quicksort/
// https://twitter.com/mathias/status/1036626116654637057?lang=en
// https://www.toptal.com/developers/sorting-algorithms/quick-sort
