= Quick Sort

Quick sort is an efficient sorting algorithm that uses "divide and conquer" paradigm to accomplish it task faster. It uses auxiliary memory in the process of sorting.

== Quick Sort Implementation

Quick sort implementation is as follows

.Quick Sort Algorithm
. It moves one element at a time (from left to right). Everything on the left of the current element is already sorted, while everything to the right is not.
. Start with the first element and make it the current element.
. Compare elements to right of the current element.
. Quick up big values to the right of the array.
.. Swap elements if the previous element is bigger than the previous one.
. Move the current pointer to the next element and repeat for the rest of the array


Let's convert these words into code!

.Quick Sort implementation in JavaScript (QuickSort)
[source, javascript]
----
include::{codedir}/algorithms/sorting/Quick-sort.js[tag=sort, indent=0]
----
<1> Convert any kind of iterable (array, sets, etc.) into an array

As you can see this function is just a wrapper to transform things to array. The heavy lifting is done in `splitSort` as you can see below.

.Quick Sort implementation in JavaScript (splitSort)
[source, javascript]
----
include::{codedir}/algorithms/sorting/Quick-sort.js[tag=splitSort, indent=0]
----
<1> Recursively divide the array in half until two or less elements are left.
<2> Sort two or less elements.
<3> Quick back the sorted halves in ascending order.

Quick sort has a <<Quadratic>> running time, as you might infer from the nested for-loop.

== Quick Sort Properties

- Time Complexity: [big]#✅# <<Linearithmic>> _O(n log n)_
- Space Complexity: [big]#⚠️# <<Linear>> _O(n)_
- <<Stable>>: [big]#✅# Yes
- <<In-place>>: [big]#⛔️️️️️# No, it requires auxiliary memory O(n).
- <<Online>>: [big]#️️️️️️️⛔️️️️️# No, new elements will require to sort the whole array.
- <<Adaptive>>: [big]#️️️️️️️⛔️️️️️# No, mostly sorted array takes the same time O(n log n).
- Recursive: Yes
