ifndef::imagesdir[]
:imagesdir: ../images
:codedir: ../../src
endif::[]

= Sorting Properties

Sorting implementations with the same time complexity might manipulate the data differently. We want to understand these differences so we can be aware of the side-effects it will have on data or extra resources they will require. For instance, some solutions will need auxiliary memory to store temporary data while sorting while others can do it in place.

Sorting properties are stable, adaptive, online and in-place. Let's go one by one.

== Stable
(((Sorting, stable)))
An ((stable sorting)) algorithms keep the relative order of items with the same comparison criteria.

This especially useful when you want to sort on multiple phases.

.Let's say you have the following data:
[source, javascript]
----
const users = [
  { name: 'Bob', age: 32 },
  { name: 'Alice', age: 30 },
  { name: 'Don', age: 30 },
  { name: 'Charly', age: 32 },
];
----

.If you sort by `name` you would have:
[source, javascript]
----
[
  { name: 'Alice', age: 30 },
  { name: 'Bob', age: 32 },
  { name: 'Charly', age: 32 },
  { name: 'Don', age: 30 },
];
----

Then, here comes the _critical_ part, if you sort by `age` you might get (at least two) different results.

.If the sorting algorithm is *stable*; it should keep the items with the same age ordered by `name`:
[source, javascript]
----
[
  { name: 'Alice', age: 30 },
  { name: 'Don', age: 30 },
  { name: 'Bob', age: 32 },
  { name: 'Charly', age: 32 },
];
----

.However, if the sorting is *not stable*, then you will lose the relative order of the items and get something like this:
[source, javascript]
----
[
  { name: 'Don', age: 30 },
  { name: 'Alice', age: 30 },
  { name: 'Charly', age: 32 },
  { name: 'Bob', age: 32 },
];
----

Both results are sorted by `age`; however, having a stable sorting is better if you want to keep the relative position of data with the same value.

== In-place
(((Sorting, in-place)))
An ((in-place sorting)) algorithm would have a _space complexity_ of O(1). In other words, it does not use any other auxiliary memory because it moves the items in the collection itself.
No requiring extra memory for sorting is especially useful for memory constraint environments like robotics, smart devices, or embedded systems in appliances.

== Online
(((Sorting, online)))
It can sort a list as it receives it.
((Online sorting)) algorithms don't have to re-sort the whole collection for every new item added.

== Adaptive
(((Sorting, adaptive)))
Algorithms with ((adaptive sorting)) run faster, close to _O(n)_, on an already sorted (or partially sorted) collection.
