[preface]
= Preface

This book is intended for programmers who want to go deeper into understanding the most common data structures and algorithms.
Even though you can use them without knowing how they work, it's handy to know when to use one over the other. This book gives you a tool for analyzing trade-offs. When something is slow, you would know how to analyze the code for better performance.

The concepts in this book can be applied to any programming language. However, instead of doing examples on pseudo-code we are going to use JavaScript to implement the examples. JavaScript is the lingua franca of the web and nowadays is growing its usages in the backend, IOT, and others.

The following admonitions are used to highlight content

IMPORTANT: Reword essential concepts. Good for memorizing, tweeting and sharing.

.Side Note with Title
[NOTE]
====
Side notes. E.g. provide language specific: BigInt, charCodeAt...
[source,javascript]
----
function a(test) {
  return `${test}`;
}
----
====

Legend:

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING
