= Preface

== What is in this book?

_{book-title}_ is a book that can be read from cover to cover, where each section builds on top of the previous one. Also, it can be used as a reference manual where developers can refresh certain topics before an interview or looking for ideas to solve a problem optimally.

This publication is designed to be concise, intending to serve software developers looking to get a firm conceptual understanding of data structures in a quick yet in-depth fashion. After reading this book, the reader should have a fundamental understanding of algorithms, including when and where to apply it, what are the trade-offs of using one data structure over the other. The reader will then be able to make intelligent decisions about algorithms and data structures in their projects require.

== Who this book is for

This book is for JavaScript software developers looking to improve their problem-solving skills.

== What you need for this book

You will need Node.js. The book code was tested against Node.js v10.12, but newer versions should also work.

== Conventions

We use a number of typographical conventions within this book that distinguish between different kinds of information.

Code in the text, including commands, variables, file names, CSS class names, and property names are shown as follows:

[example]
The `edgeDirection` parameter allow us to use one class for both undirected and directed graphs.

A block of code is set out as follows. It may be colored, depending on the format in which you're reading this book.

[source,html]
.src/app/search/search.component.html
----
<form>
  <input type="search" name="query" [(ngModel)]="query" (keyup.enter)="search()">
  <button type="button" (click)="search()">Search</button>
</form>
----

[source,java]
.src/main/java/demo/DemoApplication.java
----
@RestController
class BlogController {
    private final BlogRepository repository;

    // Yay! No annotations needed for constructor injection in Spring 4.3+.
    public BlogController(BlogRepository repository) {
        this.repository = repository;
    }

    @RequestMapping("/blogs")
    Collection<Blog> list() {
        return repository.findAll();
    }
}
----

When we want to draw your attention to certain lines of code, those lines are annotated using numbers accompanied by brief descriptions.

[source,javascript]
----
export class SearchComponent {
  constructor(private searchService: SearchService) {} <1>

  search(): void { <2>
    this.searchService.search(this.query).subscribe( <3>
      data => { this.searchResults = data; },
      error => console.log(error)
    );
  }
}
----
<1> To inject `SearchService` into `SearchComponent`, add it as a parameter to the constructors's argument list.
<2> `search()` is a method that's called from the HTML's `<button>`, wired up using the `(click)` event handler.
<3> `this.query` is a variable that's wired to `<input>` using two-way binding with `[(ngModel)]="query"`.


TIP: Tips are shown using callouts like this.

WARNING: Warnings are shown using callouts like this.

.Sidebar
****
Additional information about a certain topic may be displayed in a sidebar like this one.
****

Finally, this text shows what a quote looks like:

"In the end, it's not the years in your life that count. It's the life in your years."
-- Abraham Lincoln

== Reader feedback

We always welcome feedback from our readers. Let us know what you thought about this book — what you liked or disliked. Reader feedback helps us develop titles that deliver the most value to you.

To send us feedback, e-mail us at feedback@infoq.com, send a tweet to @jhipster_book, or post a question on Stack Overflow using the "`jhipster`" tag.

If you're interested in writing a mini-book for InfoQ, see http://www.infoq.com/minibook-guidelines.
