= Fibonacci Sequence with Dynamic Programming

Let's solve the same Fibonacci problem but this time with dynamic programming.

When we have recursive functions doing duplicated work is the perfect place for a dynamic programming optimization. We can save (or cache) the results of previous operations and speed up future computations.

.Recursive Fibonacci Implemenation using Dynamic Programming
[source, javascript]
----
include::{codedir}/algorithms/fibanacci-dynamic-programming.js[tag=snippet,indent=0]
----

This implementation checks if we already calculated the value in the past, if not it will save it for later use.

[graphviz, Recursive Fibonacci call tree with dp, svg]
....
graph G {
    "fib(5)" -- { "fib(4)" }
    "fib(4)" -- { "fib(3)" }
    "fib(3)" -- { "fib(2)" }
    "fib(2)" -- { "fib(1)", "fib(0)" }
}
....

This looks pretty linear now. It's runtime _O(n)_!

TIP: Saving previous results for later is a technique called "memoization" and is very common to optimize recursive algorithms with exponential time complexity.
