# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# https://github.com/akosma/eBook-Template
# brew install plantuml glib gdk-pixbuf cairo pango cmake libxml2 pkg-config
gem 'asciidoctor'

gem 'pygments.rb'
gem 'kindlegen'
gem 'asciimath'
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'epubcheck'

# brew link gettext --force
# brew install pkg-config
# https://github.com/gjtorikian/mathematical - run script/bootstrap; MATHEMATICAL_USE_SYSTEM_LASEM=1 gem install mathematical
gem 'asciidoctor-mathematical'

# --pre
gem 'asciidoctor-pdf'
gem 'asciidoctor-epub3'
gem 'asciidoctor-html5s' # gem install --pre asciidoctor-html5s

# cd ~/Library/Fonts; \
# curl -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmex10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmmi10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmr10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmsy10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/esint10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/eufm10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/msam10.ttf \
#      -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/msbm10.ttf

gem "prawn-gmagick", "~> 0.0.8" # brew install GraphicsMagick
